---
title: "Untitled"
output: html_document
date: "2023-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Install and load necessary packages
packages <- c("devtools","here","dplyr","tidyverse","readxl","writexl","hunspell")
for (package in packages) {
  if (!requireNamespace(package, quietly = TRUE)) {
    install.packages(package)
  }
}
lapply(packages,library, character.only=T)
```

```{r}
#Install and load embedR
if (!requireNamespace("embedR", quietly = TRUE)) {
    # If not installed, install it using devtools
    devtools::install_github("dwulff/embedR")
}

library("embedR")
```

```{r}
set.seed(26)
#read in final dataset
energyact_fin <- read_xlsx(here::here("data","energyact_final.xlsx"))

#set api tokens
embedR::er_set_tokens("cohere" = "Snf1BGQYiAqyfdCSW8UawiepcZiDLqmriSR2aKN4","huggingface"="x","openai" = "x")

embedding = energyact_fin$word%>%
  er_embed(api="cohere",model="embed-multilingual-v3.0")

#save embeddings as R object
saveRDS(embedding, here::here("data","embedding.rds"))

#load embeddings as R object
#embedding <- readRDS(here::here("data","embedding.rds"))

#load result as R object
#resultfin <- readRDS(here::here("data","resultfin_emb.rds"))
```

```{r}
set.seed(26)
result_fin = embedding %>%

  # group similar texts
  er_group(method = "fuzzy",threshold = 0.9) %>%

  # generate 2D projection
  er_project(method = "umap") %>%

  # cluster projection
  er_cluster(method = "louvain",resolution = 1.50) %>%

  # produce data frame
  er_frame()

#save result as rds
saveRDS(result_fin,here::here("data","resultfin_emb.rds"))
```

```{r,echo=F,eval=F}
set.seed(26)
result2 = embedding %>%

  # group similar texts
  er_group(method = "fuzzy",threshold = 0.4) %>%

  # generate 2D projection
  er_project(method = "umap") %>%

  # cluster projection
  er_cluster(method = "louvain",resolution = 1.5) %>%

  # produce data frame
  er_frame()

#save result as rds
saveRDS(result2,here::here("data","result_emb2.rds"))
```


```{r}
# re-label text groups

#relabel groups
#result$new_label <- er_infer_labels(result$group_texts,"openai")

# visualize
#result %>% plot()

#Cohere's generative model command-nightly
```

```{r,eval=F,echo=F}
resultfin%>%
  plot(color = cluster,
       size = group_size,
       label = text,
       label_filter = group_size > 20)
```

```{r}
result_fin$group_texts <- sapply(result_fin$group_texts, toString)
write_xlsx(result_fin, here::here("data","embedR_resfin.xlsx"))
#cluster 1 economy
#cluster 13 environmental protection
```

```{r,eval=F,echo=F}
result2$group_texts <- sapply(result2$group_texts, toString)
write_xlsx(result2, here::here("data","embedR_res2.xlsx"))
```



