---
title: "Final_EnergyAct"
output: html_document
date: "2023-11-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Install and load necessary packages
packages <- c("here","tidyverse","dplyr","readxl","writexl","umap","dbscan","fpc","Rtsne","glmnet","stats")
for (package in packages) {
  if (!requireNamespace(package, quietly = TRUE)) {
    install.packages(package)
  }
}
lapply(packages,library, character.only=T)
```

Reading in the data

```{r}
#Read in the datasets "Embeddings_text", "features", & wordEmbeddings and merge them
sentences <- read.csv(here("data","Embeddings_text.csv"))
structure <- read_excel(here("data","wordEmbeddings.xlsx"))
embeddings <- read.csv(here("data","features_3.csv"))

# Modify the structure dataframe
structure <- structure %>%
  mutate(sentence = sentences$word.comment) %>%
  select(-`word+comment`)

# Combine structure and embeddings dataframes
energyact <- cbind(structure, select(embeddings,-1))

# Import the new CSV file
additional_data <- read.csv(here("data","all_surveys.csv"))

# Left join on the 'personID' column of climateact with the 'participantID' column of additional_data
energyact <- left_join(energyact, 
                        select(additional_data, participantID, intendedVote, ratingLaw, mean_valence_macro), 
                        by = c("personID" = "participantID"))


# Rearrange the columns to place the new columns at positions 11-13
cols_new <- c(1:10, (ncol(energyact)-2):ncol(energyact), 11:(ncol(energyact)-3))



energyact <- energyact[, cols_new]

# Check the first few rows of the merged data to ensure correctness
head(energyact)
```

```{r}
embedding_cols <- paste("X", 0:1023, sep = "")

#Visualize embeddings
embeddings_energyact <- as.matrix(energyact[, embedding_cols])
# Perform t-SNE
set.seed(123) # for reproducibility
tsne_energyact <- Rtsne(embeddings_energyact, is_distance = FALSE, perplexity = 30, check_duplicates = FALSE)

# Plot t-SNE results
tsne_plot <- ggplot(NULL, aes(x = tsne_energyact$Y[, 1], y = tsne_energyact$Y[, 2])) +
  geom_point(alpha = 0.6) +
  labs(title = "t-SNE of embeddings")

print(tsne_plot)
```

```{r}
#Principal Component Analysis to reduce to important dimensions for new embeddings
set.seed(123)

# Applying PCA
scaled_embeddings <- scale(embeddings_energyact)
pca_result <- prcomp(scaled_embeddings, center = TRUE, scale. = TRUE)

# Plotting the variance explained by each principal component
explained_variance_ratio <- pca_result$sdev^2 / sum(pca_result$sdev^2)
cum_explained_variance <- cumsum(explained_variance_ratio)
plot(explained_variance_ratio, type = "b", main="Explained Variance by Principal Components",
     xlab = "Principal Component", ylab = "Explained Variance Ratio")

plot(cum_explained_variance, type = "b", main="Cumulative Explained Variance",
     xlab = "Number of Principal Components", ylab = "Cumulative Explained Variance Ratio",
     ylim=c(0.8,1), yaxp=c(0.8,1,4))  # Here, it's divided into 0.8, 0.85, 0.9, 0.95, 1

#By inspecting the Cumulative graph, choose what number of components explain 95% of variance
```

```{r}
# Project the data onto the first 300 principal components
set.seed(123)
pca_energyact <- pca_result$x[, 1:300]
```

```{r}
# Apply DBSCAN on PCA reduced set
set.seed(123)
db_result <- dbscan::dbscan(pca_energyact, eps = 15, minPts = 5)

# Count of data points in each cluster
cluster_counts <- table(db_result$cluster)

# Display the clustering results
print(cluster_counts)

# Number of clusters (excluding noise)
num_clusters <- length(unique(db_result$cluster)) - 1  # Subtracting 1 to exclude noise
cat("Number of clusters:", num_clusters, "\n")

# Number of noise points
num_noise <- sum(db_result$cluster == 0)
cat("Number of noise points:", num_noise, "\n")
```

```{r}
#Create dataframe to inspect cluster with words
# Extract columns 2:12 from the climateact_word dataset
energyact_selected <- energyact[, 2:12]

# Add the cluster assignments from PCA to the extracted dataframe
energyact_selected$cluster <- db_result$cluster

# Rename the resulting dataframe
energyact_clustered <- energyact_selected
write_xlsx(energyact_clustered, "energyact_clustered.xlsx")

View(energyact_clustered)
```

```{r}
#Create dataset of noise points to cluster them
energyact_rest <- cbind(energyact[,2:12],energyact_clustered$cluster,scaled_embeddings)
energyact_rest <- energyact_rest%>%
  filter(energyact_clustered$cluster==0)%>%
  rename(cluster = `energyact_clustered$cluster`)
embeddings_rest <- as.matrix(energyact_rest[, embedding_cols])

# Perform t-SNE
set.seed(123) # for reproducibility
tsne_energyact_rest <- Rtsne(embeddings_rest, is_distance = FALSE, perplexity = 30, check_duplicates = FALSE)

# Plot t-SNE results
plot_rest <- ggplot(NULL, aes(x = tsne_energyact_rest$Y[, 1], y = tsne_energyact_rest$Y[, 2])) +
  geom_point(alpha = 0.6) +
  labs(title = "t-SNE of rest embeddings")

print(plot_rest)
```

```{r}
#Principal Component Analysis to reduce to important dimensions for rest embeddings
set.seed(123)

# Applying PCA
pca_result_rest <- prcomp(embeddings_rest, center = TRUE, scale. = TRUE)

# Plotting the variance explained by each principal component
explained_variance_ratio_rest <- pca_result_rest$sdev^2 / sum(pca_result_rest$sdev^2)
cum_explained_variance_rest <- cumsum(explained_variance_ratio_rest)
plot(explained_variance_ratio_rest, type = "b", main="Explained Variance by Principal Components",
     xlab = "Principal Component", ylab = "Explained Variance Ratio")

plot(cum_explained_variance_rest, type = "b", main="Cumulative Explained Variance",
     xlab = "Number of Principal Components", ylab = "Cumulative Explained Variance Ratio",
     ylim=c(0.8,1), yaxp=c(0.8,1,4))  # Here, it's divided into 0.8, 0.85, 0.9, 0.95, 1

#By inspecting the Cumulative graph, choose what number of components explain 95% of variance
```

```{r}
# Project the data onto the first 300 principal components
pca_rest <- pca_result_rest$x[, 1:300]
```

```{r}
# Apply DBSCAN on PCA reduced set
set.seed(123)
db_result_rest <- dbscan::dbscan(pca_rest, eps = 20, minPts = 3)

# Count of data points in each cluster
cluster_counts_rest <- table(db_result_rest$cluster)

# Display the clustering results
print(cluster_counts_rest)

# Number of clusters (excluding noise)
num_clusters_rest <- length(unique(db_result_rest$cluster)) - 1  # Subtracting 1 to exclude noise
cat("Number of clusters:", num_clusters_rest, "\n")

# Number of noise points
num_noise_rest <- sum(db_result_rest$cluster == 0)
cat("Number of noise points:", num_noise_rest, "\n")
```

```{r}
#Create dataframe to inspect rest cluster with words
# Extract columns 2:12 from the energyact dataset
energyact_rest_clustered <- energyact_rest[, 1:11]

energyact_rest_clustered$rest_cluster <- db_result_rest$cluster


#Write Xl file
write_xlsx(energyact_rest_clustered, "energyact_rest.xlsx")
```

```{r}
#Repeat the procedure again
#Create dataset of noise points to cluster them
energyact_rest2 <- cbind(energyact_rest_clustered[,1:12],embeddings_rest)
energyact_rest2 <- energyact_rest2%>%
  filter(rest_cluster==0)%>%
  rename(cluster = `rest_cluster`)
embeddings_rest2 <- as.matrix(energyact_rest2[, embedding_cols])

# Perform t-SNE
set.seed(123) # for reproducibility
tsne_energyact_rest2 <- Rtsne(embeddings_rest2, is_distance = FALSE, perplexity = 30, check_duplicates = FALSE)

# Plot t-SNE results
plot_rest2 <- ggplot(NULL, aes(x = tsne_energyact_rest2$Y[, 1], y = tsne_energyact_rest2$Y[, 2])) +
  geom_point(alpha = 0.6) +
  labs(title = "t-SNE of rest embeddings")

print(plot_rest2)
```

```{r}
#Principal Component Analysis to reduce to important dimensions for rest embeddings
set.seed(123)

# Applying PCA
pca_result_rest2 <- prcomp(embeddings_rest2, center = TRUE, scale. = TRUE)

# Plotting the variance explained by each principal component
explained_variance_ratio_rest2 <- pca_result_rest2$sdev^2 / sum(pca_result_rest2$sdev^2)
cum_explained_variance_rest2 <- cumsum(explained_variance_ratio_rest2)
plot(explained_variance_ratio_rest2, type = "b", main="Explained Variance by Principal Components",
     xlab = "Principal Component", ylab = "Explained Variance Ratio")

plot(cum_explained_variance_rest2, type = "b", main="Cumulative Explained Variance",
     xlab = "Number of Principal Components", ylab = "Cumulative Explained Variance Ratio",
     ylim=c(0.8,1), yaxp=c(0.8,1,4))  # Here, it's divided into 0.8, 0.85, 0.9, 0.95, 1

#By inspecting the Cumulative graph, choose what number of components explain 95% of variance
```

```{r}
# Project the data onto the first 300 principal components
pca_rest2 <- pca_result_rest2$x[, 1:300]
```

```{r}
# Apply DBSCAN on PCA reduced set
set.seed(123)
db_result_rest2 <- dbscan::dbscan(pca_rest2, eps = 25, minPts = 3)

# Count of data points in each cluster
cluster_counts_rest2 <- table(db_result_rest2$cluster)

# Display the clustering results
print(cluster_counts_rest2)

# Number of clusters (excluding noise)
num_clusters_rest2 <- length(unique(db_result_rest2$cluster)) - 1  # Subtracting 1 to exclude noise
cat("Number of clusters:", num_clusters_rest2, "\n")

# Number of noise points
num_noise_rest2 <- sum(db_result_rest2$cluster == 0)
cat("Number of noise points:", num_noise_rest2, "\n")
```

```{r}
#Create dataframe to inspect rest cluster with words
# Extract columns 2:12 from the energyact dataset
energyact_rest2_clustered <- energyact_rest2[, 1:11]

energyact_rest2_clustered$rest_cluster <- db_result_rest2$cluster


#Write Xl file
write_xlsx(energyact_rest2_clustered, "energyact_rest2.xlsx")
```

```{r}
#Repeat the procedure again
#Create dataset of noise points to cluster them
energyact_rest3 <- cbind(energyact_rest2_clustered[,1:12],embeddings_rest2)
energyact_rest3 <- energyact_rest3%>%
  filter(rest_cluster==0)%>%
  rename(cluster = `rest_cluster`)
embeddings_rest3 <- as.matrix(energyact_rest3[, embedding_cols])

# Perform t-SNE
set.seed(123) # for reproducibility
tsne_energyact_rest3 <- Rtsne(embeddings_rest3, is_distance = FALSE, perplexity = 30, check_duplicates = FALSE)

# Plot t-SNE results
plot_rest3 <- ggplot(NULL, aes(x = tsne_energyact_rest3$Y[, 1], y = tsne_energyact_rest3$Y[, 2])) +
  geom_point(alpha = 0.6) +
  labs(title = "t-SNE of rest embeddings")

print(plot_rest3)
```

```{r}
#Principal Component Analysis to reduce to important dimensions for rest embeddings
set.seed(123)

# Applying PCA
pca_result_rest3 <- prcomp(embeddings_rest3, center = TRUE, scale. = TRUE)

# Plotting the variance explained by each principal component
explained_variance_ratio_rest3 <- pca_result_rest3$sdev^2 / sum(pca_result_rest3$sdev^2)
cum_explained_variance_rest3 <- cumsum(explained_variance_ratio_rest3)
plot(explained_variance_ratio_rest3, type = "b", main="Explained Variance by Principal Components",
     xlab = "Principal Component", ylab = "Explained Variance Ratio")

plot(cum_explained_variance_rest3, type = "b", main="Cumulative Explained Variance",
     xlab = "Number of Principal Components", ylab = "Cumulative Explained Variance Ratio",
     ylim=c(0.8,1), yaxp=c(0.8,1,4))  # Here, it's divided into 0.8, 0.85, 0.9, 0.95, 1

#By inspecting the Cumulative graph, choose what number of components explain 95% of variance
```

```{r}
# Project the data onto the first 300 principal components
pca_rest3 <- pca_result_rest3$x[, 1:300]
```

```{r}
# Apply DBSCAN on PCA reduced set
set.seed(123)
db_result_rest3 <- dbscan::dbscan(pca_rest3, eps = 27, minPts = 3)

# Count of data points in each cluster
cluster_counts_rest3 <- table(db_result_rest3$cluster)

# Display the clustering results
print(cluster_counts_rest3)

# Number of clusters (excluding noise)
num_clusters_rest3 <- length(unique(db_result_rest3$cluster)) - 1  # Subtracting 1 to exclude noise
cat("Number of clusters:", num_clusters_rest3, "\n")

# Number of noise points
num_noise_rest3 <- sum(db_result_rest3$cluster == 0)
cat("Number of noise points:", num_noise_rest3, "\n")
```

```{r}
#Create dataframe to inspect rest cluster with words
# Extract columns 2:12 from the energyact dataset
energyact_rest3_clustered <- energyact_rest3[, 1:11]

energyact_rest3_clustered$rest_cluster <- db_result_rest3$cluster


#Write Xl file
write_xlsx(energyact_rest3_clustered, "energyact_rest3.xlsx")
```

```{r}
#Repeat the procedure again
#Create dataset of noise points to cluster them
energyact_rest4 <- cbind(energyact_rest3_clustered,embeddings_rest3)
energyact_rest4 <- energyact_rest4%>%
  filter(rest_cluster==0)%>%
  rename(cluster = `rest_cluster`)
embeddings_rest4 <- as.matrix(energyact_rest4[, embedding_cols])

# Perform t-SNE
set.seed(123) # for reproducibility
tsne_energyact_rest4 <- Rtsne(embeddings_rest4, is_distance = FALSE, perplexity = 30, check_duplicates = FALSE)

# Plot t-SNE results
plot_rest4 <- ggplot(NULL, aes(x = tsne_energyact_rest4$Y[, 1], y = tsne_energyact_rest4$Y[, 2])) +
  geom_point(alpha = 0.6) +
  labs(title = "t-SNE of rest embeddings")

print(plot_rest4)
```

```{r}
#Principal Component Analysis to reduce to important dimensions for rest embeddings
set.seed(123)

# Applying PCA
pca_result_rest4 <- prcomp(embeddings_rest4, center = TRUE, scale. = TRUE)

# Plotting the variance explained by each principal component
explained_variance_ratio_rest4 <- pca_result_rest4$sdev^2 / sum(pca_result_rest4$sdev^2)
cum_explained_variance_rest4 <- cumsum(explained_variance_ratio_rest4)
plot(explained_variance_ratio_rest4, type = "b", main="Explained Variance by Principal Components",
     xlab = "Principal Component", ylab = "Explained Variance Ratio")

plot(cum_explained_variance_rest4, type = "b", main="Cumulative Explained Variance",
     xlab = "Number of Principal Components", ylab = "Cumulative Explained Variance Ratio",
     ylim=c(0.8,1), yaxp=c(0.8,1,4))  # Here, it's divided into 0.8, 0.85, 0.9, 0.95, 1

#By inspecting the Cumulative graph, choose what number of components explain 95% of variance
```

```{r}
# Project the data onto the first 300 principal components
pca_rest4 <- pca_result_rest4$x[, 1:300]
```

```{r}
# Apply DBSCAN on PCA reduced set
set.seed(123)
db_result_rest4 <- dbscan::dbscan(pca_rest4, eps = 28, minPts = 3)

# Count of data points in each cluster
cluster_counts_rest4 <- table(db_result_rest4$cluster)

# Display the clustering results
print(cluster_counts_rest4)

# Number of clusters (excluding noise)
num_clusters_rest4 <- length(unique(db_result_rest4$cluster)) - 1  # Subtracting 1 to exclude noise
cat("Number of clusters:", num_clusters_rest4, "\n")

# Number of noise points
num_noise_rest4 <- sum(db_result_rest4$cluster == 0)
cat("Number of noise points:", num_noise_rest4, "\n")
```

```{r}
#Create dataframe to inspect rest cluster with words
# Extract columns 2:12 from the energyact dataset
energyact_rest4_clustered <- energyact_rest4[, 1:11]

energyact_rest4_clustered$rest_cluster <- db_result_rest4$cluster


#Write Xl file
write_xlsx(energyact_rest4_clustered, "energyact_rest4.xlsx")
```

```{r}
#Repeat the procedure again
#Create dataset of noise points to cluster them
energyact_rest5 <- cbind(energyact_rest4_clustered,embeddings_rest4)
energyact_rest5 <- energyact_rest5%>%
  filter(rest_cluster==0)%>%
  rename(cluster = `rest_cluster`)
embeddings_rest5 <- as.matrix(energyact_rest5[, embedding_cols])

# Perform t-SNE
set.seed(123) # for reproducibility
tsne_energyact_rest5 <- Rtsne(embeddings_rest5, is_distance = FALSE, perplexity = 30, check_duplicates = FALSE)

# Plot t-SNE results
plot_rest5 <- ggplot(NULL, aes(x = tsne_energyact_rest5$Y[, 1], y = tsne_energyact_rest5$Y[, 2])) +
  geom_point(alpha = 0.6) +
  labs(title = "t-SNE of rest embeddings")

print(plot_rest5)
```

```{r}
#Principal Component Analysis to reduce to important dimensions for rest embeddings
set.seed(123)

# Applying PCA
pca_result_rest5 <- prcomp(embeddings_rest5, center = TRUE, scale. = TRUE)

# Plotting the variance explained by each principal component
explained_variance_ratio_rest5 <- pca_result_rest5$sdev^2 / sum(pca_result_rest5$sdev^2)
cum_explained_variance_rest5 <- cumsum(explained_variance_ratio_rest5)
plot(explained_variance_ratio_rest5, type = "b", main="Explained Variance by Principal Components",
     xlab = "Principal Component", ylab = "Explained Variance Ratio")

plot(cum_explained_variance_rest5, type = "b", main="Cumulative Explained Variance",
     xlab = "Number of Principal Components", ylab = "Cumulative Explained Variance Ratio",
     ylim=c(0.8,1), yaxp=c(0.8,1,4))  # Here, it's divided into 0.8, 0.85, 0.9, 0.95, 1

#By inspecting the Cumulative graph, choose what number of components explain 95% of variance
```

```{r}
# Project the data onto the first 300 principal components
pca_rest5 <- pca_result_rest5$x[, 1:300]
```

```{r}
# Apply DBSCAN on PCA reduced set
set.seed(123)
db_result_rest5 <- dbscan::dbscan(pca_rest5, eps = 29, minPts = 3)

# Count of data points in each cluster
cluster_counts_rest5 <- table(db_result_rest5$cluster)

# Display the clustering results
print(cluster_counts_rest5)

# Number of clusters (excluding noise)
num_clusters_rest5 <- length(unique(db_result_rest5$cluster)) - 1  # Subtracting 1 to exclude noise
cat("Number of clusters:", num_clusters_rest5, "\n")

# Number of noise points
num_noise_rest5 <- sum(db_result_rest5$cluster == 0)
cat("Number of noise points:", num_noise_rest5, "\n")
```

```{r}
#Create dataframe to inspect rest cluster with words
# Extract columns 2:12 from the energyact dataset
energyact_rest5_clustered <- energyact_rest5[, 1:11]

energyact_rest5_clustered$rest_cluster <- db_result_rest5$cluster


#Write Xl file
write_xlsx(energyact_rest5_clustered, "energyact_rest5.xlsx")
```

```{r}
#Repeat the procedure again
#Create dataset of noise points to cluster them
energyact_rest6 <- cbind(energyact_rest5_clustered,embeddings_rest5)
energyact_rest6 <- energyact_rest6%>%
  filter(rest_cluster==0)%>%
  rename(cluster = `rest_cluster`)
embeddings_rest6 <- as.matrix(energyact_rest6[, embedding_cols])

# Perform t-SNE
set.seed(123) # for reproducibility
tsne_energyact_rest6 <- Rtsne(embeddings_rest6, is_distance = FALSE, perplexity = 30, check_duplicates = FALSE)

# Plot t-SNE results
plot_rest6 <- ggplot(NULL, aes(x = tsne_energyact_rest6$Y[, 1], y = tsne_energyact_rest6$Y[, 2])) +
  geom_point(alpha = 0.6) +
  labs(title = "t-SNE of rest embeddings")

print(plot_rest6)
```

```{r}
#Principal Component Analysis to reduce to important dimensions for rest embeddings
set.seed(123)

# Applying PCA
pca_result_rest6 <- prcomp(embeddings_rest6, center = TRUE, scale. = TRUE)

# Plotting the variance explained by each principal component
explained_variance_ratio_rest6 <- pca_result_rest6$sdev^2 / sum(pca_result_rest6$sdev^2)
cum_explained_variance_rest6 <- cumsum(explained_variance_ratio_rest6)
plot(explained_variance_ratio_rest6, type = "b", main="Explained Variance by Principal Components",
     xlab = "Principal Component", ylab = "Explained Variance Ratio")

plot(cum_explained_variance_rest6, type = "b", main="Cumulative Explained Variance",
     xlab = "Number of Principal Components", ylab = "Cumulative Explained Variance Ratio",
     ylim=c(0.8,1), yaxp=c(0.8,1,4))  # Here, it's divided into 0.8, 0.85, 0.9, 0.95, 1

#By inspecting the Cumulative graph, choose what number of components explain 95% of variance
```

```{r}
# Project the data onto the first 300 principal components
pca_rest6 <- pca_result_rest6$x[, 1:300]
```

```{r}
# Apply DBSCAN on PCA reduced set
set.seed(123)
db_result_rest6 <- dbscan::dbscan(pca_rest6, eps = 30, minPts = 3)

# Count of data points in each cluster
cluster_counts_rest6 <- table(db_result_rest6$cluster)

# Display the clustering results
print(cluster_counts_rest6)

# Number of clusters (excluding noise)
num_clusters_rest6 <- length(unique(db_result_rest6$cluster)) - 1  # Subtracting 1 to exclude noise
cat("Number of clusters:", num_clusters_rest6, "\n")

# Number of noise points
num_noise_rest6 <- sum(db_result_rest6$cluster == 0)
cat("Number of noise points:", num_noise_rest6, "\n")
```

```{r}
#Create dataframe to inspect rest cluster with words
# Extract columns 2:12 from the energyact dataset
energyact_rest6_clustered <- energyact_rest6[, 1:11]

energyact_rest6_clustered$rest_cluster <- db_result_rest6$cluster


#Write Xl file
write_xlsx(energyact_rest6_clustered, "energyact_rest6.xlsx")
```

```{r}
#Repeat the procedure again
#Create dataset of noise points to cluster them
energyact_rest7 <- cbind(energyact_rest6_clustered,embeddings_rest6)
energyact_rest7 <- energyact_rest7%>%
  filter(rest_cluster==0)%>%
  rename(cluster = `rest_cluster`)
embeddings_rest7 <- as.matrix(energyact_rest7[, embedding_cols])

# Perform t-SNE
set.seed(123) # for reproducibility
tsne_energyact_rest7 <- Rtsne(embeddings_rest7, is_distance = FALSE, perplexity = 30, check_duplicates = FALSE)

# Plot t-SNE results
plot_rest7 <- ggplot(NULL, aes(x = tsne_energyact_rest7$Y[, 1], y = tsne_energyact_rest7$Y[, 2])) +
  geom_point(alpha = 0.6) +
  labs(title = "t-SNE of rest embeddings")

print(plot_rest7)
```

```{r}
#Principal Component Analysis to reduce to important dimensions for rest embeddings
set.seed(123)

# Applying PCA
pca_result_rest7 <- prcomp(embeddings_rest7, center = TRUE, scale. = TRUE)

# Plotting the variance explained by each principal component
explained_variance_ratio_rest7 <- pca_result_rest7$sdev^2 / sum(pca_result_rest7$sdev^2)
cum_explained_variance_rest7 <- cumsum(explained_variance_ratio_rest7)
plot(explained_variance_ratio_rest7, type = "b", main="Explained Variance by Principal Components",
     xlab = "Principal Component", ylab = "Explained Variance Ratio")

plot(cum_explained_variance_rest7, type = "b", main="Cumulative Explained Variance",
     xlab = "Number of Principal Components", ylab = "Cumulative Explained Variance Ratio",
     ylim=c(0.8,1), yaxp=c(0.8,1,4))  # Here, it's divided into 0.8, 0.85, 0.9, 0.95, 1

#By inspecting the Cumulative graph, choose what number of components explain 95% of variance
```

```{r}
# Project the data onto the first 300 principal components
pca_rest7 <- pca_result_rest7$x[, 1:300]
```

```{r}
# Apply DBSCAN on PCA reduced set
set.seed(123)
db_result_rest7 <- dbscan::dbscan(pca_rest7, eps = 31, minPts = 3)

# Count of data points in each cluster
cluster_counts_rest7 <- table(db_result_rest7$cluster)

# Display the clustering results
print(cluster_counts_rest7)

# Number of clusters (excluding noise)
num_clusters_rest7 <- length(unique(db_result_rest7$cluster)) - 1  # Subtracting 1 to exclude noise
cat("Number of clusters:", num_clusters_rest7, "\n")

# Number of noise points
num_noise_rest7 <- sum(db_result_rest7$cluster == 0)
cat("Number of noise points:", num_noise_rest7, "\n")
```

```{r}
#Create dataframe to inspect rest cluster with words
# Extract columns 2:12 from the energyact dataset
energyact_rest7_clustered <- energyact_rest7[, 1:11]

energyact_rest7_clustered$rest_cluster <- db_result_rest7$cluster


#Write Xl file
write_xlsx(energyact_rest7_clustered, "energyact_rest7.xlsx")
```

```{r}
#Repeat the procedure again
#Create dataset of noise points to cluster them
energyact_rest8 <- cbind(energyact_rest7_clustered,embeddings_rest7)
energyact_rest8 <- energyact_rest8%>%
  filter(rest_cluster==0)%>%
  rename(cluster = `rest_cluster`)
embeddings_rest8 <- as.matrix(energyact_rest8[, embedding_cols])

# Perform t-SNE
set.seed(123) # for reproducibility
tsne_energyact_rest8 <- Rtsne(embeddings_rest8, is_distance = FALSE, perplexity = 30, check_duplicates = FALSE)

# Plot t-SNE results
plot_rest8 <- ggplot(NULL, aes(x = tsne_energyact_rest8$Y[, 1], y = tsne_energyact_rest8$Y[, 2])) +
  geom_point(alpha = 0.6) +
  labs(title = "t-SNE of rest embeddings")

print(plot_rest8)
```

```{r}
#Principal Component Analysis to reduce to important dimensions for rest embeddings
set.seed(123)

# Applying PCA
pca_result_rest8 <- prcomp(embeddings_rest8, center = TRUE, scale. = TRUE)

# Plotting the variance explained by each principal component
explained_variance_ratio_rest8 <- pca_result_rest8$sdev^2 / sum(pca_result_rest8$sdev^2)
cum_explained_variance_rest8 <- cumsum(explained_variance_ratio_rest8)
plot(explained_variance_ratio_rest8, type = "b", main="Explained Variance by Principal Components",
     xlab = "Principal Component", ylab = "Explained Variance Ratio")

plot(cum_explained_variance_rest8, type = "b", main="Cumulative Explained Variance",
     xlab = "Number of Principal Components", ylab = "Cumulative Explained Variance Ratio",
     ylim=c(0.8,1), yaxp=c(0.8,1,4))  # Here, it's divided into 0.8, 0.85, 0.9, 0.95, 1

#By inspecting the Cumulative graph, choose what number of components explain 95% of variance
```

```{r}
# Project the data onto the first 300 principal components
pca_rest8 <- pca_result_rest8$x[, 1:300]
```

```{r}
# Apply DBSCAN on PCA reduced set
set.seed(123)
db_result_rest8 <- dbscan::dbscan(pca_rest8, eps = 32, minPts = 3)

# Count of data points in each cluster
cluster_counts_rest8 <- table(db_result_rest8$cluster)

# Display the clustering results
print(cluster_counts_rest8)

# Number of clusters (excluding noise)
num_clusters_rest8 <- length(unique(db_result_rest8$cluster)) - 1  # Subtracting 1 to exclude noise
cat("Number of clusters:", num_clusters_rest8, "\n")

# Number of noise points
num_noise_rest8 <- sum(db_result_rest8$cluster == 0)
cat("Number of noise points:", num_noise_rest8, "\n")
```

```{r}
#Create dataframe to inspect rest cluster with words
# Extract columns 2:12 from the energyact dataset
energyact_rest8_clustered <- energyact_rest8[, 1:11]

energyact_rest8_clustered$rest_cluster <- db_result_rest8$cluster


#Write Xl file
write_xlsx(energyact_rest8_clustered, "energyact_rest8.xlsx")
```

```{r}
#Repeat the procedure again
#Create dataset of noise points to cluster them
energyact_rest9 <- cbind(energyact_rest8_clustered,embeddings_rest8)
energyact_rest9 <- energyact_rest9%>%
  filter(rest_cluster==0)%>%
  rename(cluster = `rest_cluster`)
embeddings_rest9 <- as.matrix(energyact_rest9[, embedding_cols])

# Perform t-SNE
set.seed(123) # for reproducibility
tsne_energyact_rest9 <- Rtsne(embeddings_rest9, is_distance = FALSE, perplexity = 30, check_duplicates = FALSE)

# Plot t-SNE results
plot_rest9 <- ggplot(NULL, aes(x = tsne_energyact_rest9$Y[, 1], y = tsne_energyact_rest9$Y[, 2])) +
  geom_point(alpha = 0.6) +
  labs(title = "t-SNE of rest embeddings")

print(plot_rest9)
```

```{r}
#Principal Component Analysis to reduce to important dimensions for rest embeddings
set.seed(123)

# Applying PCA
pca_result_rest9 <- prcomp(embeddings_rest9, center = TRUE, scale. = TRUE)

# Plotting the variance explained by each principal component
explained_variance_ratio_rest9 <- pca_result_rest9$sdev^2 / sum(pca_result_rest9$sdev^2)
cum_explained_variance_rest9 <- cumsum(explained_variance_ratio_rest9)
plot(explained_variance_ratio_rest9, type = "b", main="Explained Variance by Principal Components",
     xlab = "Principal Component", ylab = "Explained Variance Ratio")

plot(cum_explained_variance_rest9, type = "b", main="Cumulative Explained Variance",
     xlab = "Number of Principal Components", ylab = "Cumulative Explained Variance Ratio",
     ylim=c(0.8,1), yaxp=c(0.8,1,4))  # Here, it's divided into 0.8, 0.85, 0.9, 0.95, 1

#By inspecting the Cumulative graph, choose what number of components explain 95% of variance
```

```{r}
# Project the data onto the first 300 principal components
pca_rest9 <- pca_result_rest9$x[, 1:300]
```

```{r}
# Apply DBSCAN on PCA reduced set
set.seed(123)
db_result_rest9 <- dbscan::dbscan(pca_rest9, eps = 33, minPts = 3)

# Count of data points in each cluster
cluster_counts_rest9 <- table(db_result_rest9$cluster)

# Display the clustering results
print(cluster_counts_rest9)

# Number of clusters (excluding noise)
num_clusters_rest9 <- length(unique(db_result_rest9$cluster)) - 1  # Subtracting 1 to exclude noise
cat("Number of clusters:", num_clusters_rest9, "\n")

# Number of noise points
num_noise_rest9 <- sum(db_result_rest9$cluster == 0)
cat("Number of noise points:", num_noise_rest9, "\n")
```

```{r}
#Create dataframe to inspect rest cluster with words
# Extract columns 2:12 from the energyact dataset
energyact_rest9_clustered <- energyact_rest9[, 1:11]

energyact_rest9_clustered$rest_cluster <- db_result_rest9$cluster


#Write Xl file
write_xlsx(energyact_rest9_clustered, "energyact_rest9.xlsx")
```

```{r}
#Repeat the procedure again
#Create dataset of noise points to cluster them
energyact_rest10 <- cbind(energyact_rest9_clustered,embeddings_rest9)
energyact_rest10 <- energyact_rest10%>%
  filter(rest_cluster==0)%>%
  rename(cluster = `rest_cluster`)
embeddings_rest10 <- as.matrix(energyact_rest10[, embedding_cols])

# Perform t-SNE
set.seed(123) # for reproducibility
tsne_energyact_rest10 <- Rtsne(embeddings_rest10, is_distance = FALSE, perplexity = 30, check_duplicates = FALSE)

# Plot t-SNE results
plot_rest10 <- ggplot(NULL, aes(x = tsne_energyact_rest10$Y[, 1], y = tsne_energyact_rest10$Y[, 2])) +
  geom_point(alpha = 0.6) +
  labs(title = "t-SNE of rest embeddings")

print(plot_rest10)
```

```{r}
#Principal Component Analysis to reduce to important dimensions for rest embeddings
set.seed(123)

# Applying PCA
pca_result_rest10 <- prcomp(embeddings_rest10, center = TRUE, scale. = TRUE)

# Plotting the variance explained by each principal component
explained_variance_ratio_rest10 <- pca_result_rest10$sdev^2 / sum(pca_result_rest10$sdev^2)
cum_explained_variance_rest10 <- cumsum(explained_variance_ratio_rest10)
plot(explained_variance_ratio_rest10, type = "b", main="Explained Variance by Principal Components",
     xlab = "Principal Component", ylab = "Explained Variance Ratio")

plot(cum_explained_variance_rest10, type = "b", main="Cumulative Explained Variance",
     xlab = "Number of Principal Components", ylab = "Cumulative Explained Variance Ratio",
     ylim=c(0.8,1), yaxp=c(0.8,1,4))  # Here, it's divided into 0.8, 0.85, 0.9, 0.95, 1

#By inspecting the Cumulative graph, choose what number of components explain 95% of variance
```

```{r}
# Project the data onto the first 300 principal components
pca_rest10 <- pca_result_rest10$x[, 1:250]
```

```{r}
# Apply DBSCAN on PCA reduced set
set.seed(123)
db_result_rest10 <- dbscan::dbscan(pca_rest10, eps = 33, minPts = 3)

# Count of data points in each cluster
cluster_counts_rest10 <- table(db_result_rest10$cluster)

# Display the clustering results
print(cluster_counts_rest10)

# Number of clusters (excluding noise)
num_clusters_rest10 <- length(unique(db_result_rest10$cluster)) - 1  # Subtracting 1 to exclude noise
cat("Number of clusters:", num_clusters_rest10, "\n")

# Number of noise points
num_noise_rest10 <- sum(db_result_rest10$cluster == 0)
cat("Number of noise points:", num_noise_rest10, "\n")
```

```{r}
#Create dataframe to inspect rest cluster with words
# Extract columns 2:12 from the energyact dataset
energyact_rest10_clustered <- energyact_rest10[, 1:11]

energyact_rest10_clustered$rest_cluster <- db_result_rest10$cluster


#Write Xl file
write_xlsx(energyact_rest10_clustered, "energyact_rest10.xlsx")
```

```{r}
#Repeat the procedure again
#Create dataset of noise points to cluster them
energyact_rest11 <- cbind(energyact_rest10_clustered,embeddings_rest10)
energyact_rest11 <- energyact_rest11%>%
  filter(rest_cluster==0)%>%
  rename(cluster = `rest_cluster`)
embeddings_rest11 <- as.matrix(energyact_rest11[, embedding_cols])

# Perform t-SNE
set.seed(123) # for reproducibility
tsne_energyact_rest11 <- Rtsne(embeddings_rest11, is_distance = FALSE, perplexity = 30, check_duplicates = FALSE)

# Plot t-SNE results
plot_rest11 <- ggplot(NULL, aes(x = tsne_energyact_rest11$Y[, 1], y = tsne_energyact_rest11$Y[, 2])) +
  geom_point(alpha = 0.6) +
  labs(title = "t-SNE of rest embeddings")

print(plot_rest11)
```

```{r}
#Principal Component Analysis to reduce to important dimensions for rest embeddings
set.seed(123)

# Applying PCA
pca_result_rest11 <- prcomp(embeddings_rest11, center = TRUE, scale. = TRUE)

# Plotting the variance explained by each principal component
explained_variance_ratio_rest11 <- pca_result_rest11$sdev^2 / sum(pca_result_rest11$sdev^2)
cum_explained_variance_rest11 <- cumsum(explained_variance_ratio_rest11)
plot(explained_variance_ratio_rest11, type = "b", main="Explained Variance by Principal Components",
     xlab = "Principal Component", ylab = "Explained Variance Ratio")

plot(cum_explained_variance_rest11, type = "b", main="Cumulative Explained Variance",
     xlab = "Number of Principal Components", ylab = "Cumulative Explained Variance Ratio",
     ylim=c(0.8,1), yaxp=c(0.8,1,4))  # Here, it's divided into 0.8, 0.85, 0.9, 0.95, 1

#By inspecting the Cumulative graph, choose what number of components explain 95% of variance
```

```{r}
# Project the data onto the first 300 principal components
pca_rest11 <- pca_result_rest11$x[, 1:250]
```

```{r}
# Apply DBSCAN on PCA reduced set
set.seed(123)
db_result_rest11 <- dbscan::dbscan(pca_rest11, eps = 34, minPts = 3)

# Count of data points in each cluster
cluster_counts_rest11 <- table(db_result_rest11$cluster)

# Display the clustering results
print(cluster_counts_rest11)

# Number of clusters (excluding noise)
num_clusters_rest11 <- length(unique(db_result_rest11$cluster)) - 1  # Subtracting 1 to exclude noise
cat("Number of clusters:", num_clusters_rest11, "\n")

# Number of noise points
num_noise_rest11 <- sum(db_result_rest11$cluster == 0)
cat("Number of noise points:", num_noise_rest11, "\n")
```

```{r}
#Create dataframe to inspect rest cluster with words
# Extract columns 2:12 from the energyact dataset
energyact_rest11_clustered <- energyact_rest11[, 1:11]

energyact_rest11_clustered$rest_cluster <- db_result_rest11$cluster


#Write Xl file
write_xlsx(energyact_rest11_clustered, "energyact_rest11.xlsx")
```